package lk.vidathya.tcms.service;

public enum ServiceType {
    ATTENDANCE_SERVICE_IMPL,
    CLASS_SERVICE_IMPL,
    EXTRA_CLASS_SERVICE_IMPL,
    EXTRA_CLASS_HALL_RESERVATION_SERVICE_IMPL,
    GUARDIAN_SERVICE_IMPL,
    HALL_SERVICE_IMPL,
    HALL_RESERVATION_SERVICE_IMPL,
    INCOME_AND_EXPENDITURE_SERVICE_IMPL,
    NOT_PAID_STAFF_SALARY_SERVICE_IMPL,
    NOT_PAID_TUTOR_SALARY_SERVICE_IMPL,
    PAYMENT_SERVICE_IMPL,
    REFUND_SERVICE_IMPL,
    REGISTRATION_PAYMENT_SERVICE_IMPL,
    STAFF_SERVICE_IMPL,
    STAFF_SALARY_SERVICE_IMPL,
    STUDENTS_CLASS_SERVICE_IMPL,
    STUDENTS_SERVICE_IMPL,
    TUTOR_SERVICE_IMPL,
    TUTOR_SALARY_SERVICE_IMPL,
    USER_SERVICE_IMPL
}
