package lk.vidathya.tcms.util;

public enum Routes {
    ADDCLASS, ADDEXTRACLASS, ADDSTUDENTTOCLASSES, ATTENDANCE, CLASSFEEINFO, DASHBOARDADMIN, DASHBOARDASSISTANT,
    DASHBOARDVIEW, FINANCEMANAGE, HALL, INCOMEANDEXPENDITURE, LOGIN, MAIL, MANAGECLASSES, MANAGEEXTRACLASSES,
    MANAGEUSER, NEWUSER, PAYMENTS, PAYSTAFFSALARIES, PAYTUTORSALARIES, REFUNDS, REPORTS, REPORTSTAFFINFO, REPORTTUTORINFO,
    STAFFMANAGE,
    STAFFREGISTRATION, STAFFSALARYINFO, STUDENTMANAGE, STUDENTREGISTRATION, TUTORMANAGE,
    TUTORREGISTRATION, VIEWATTENDANCE, VIEWCLASSESINFO, VIEWCLASSFEEPAYMENTS, VIEWCLASSSTUDENTS,
    VIEWEXTRACLASSES, VIEWGUARDIANINFO, VIEWHALLINFO, VIEWHALLRESERVATIONS, VIEWINFOCONTEXT, VIEWINFORMATION,
    VIEWREFUNDS, VIEWREGISTRATIONPAYMENTS, VIEWSTAFFINFO, VIEWSTAFFSALARY,
    VIEWSTUDENTINFO, VIEWSTUDENTSCLASSES, VIEWTUTORSINFO, VIEWTUTORSSALARY

}
