package lk.vidathya.tcms.dao;

public enum DaoTypes {
    ATTENDANCE_DAO_IMPL,
    CLASS_DAO_IMPL,
    EXTRA_CLASS_DAO_IMPL,
    EXTRA_CLASS_HALL_RESERVATION_DAO_IMPL,
    GUARDIAN_DAO_IMPL,
    HALL_DAO_IMPL,
    HALL_RESERVATION_DAO_IMPL,
    INCOME_AND_EXPENDITURE_DAO_IMPL,
    NOT_PAID_STAFF_SALARY_DAO_IMPL,
    NOT_PAID_TUTOR_SALARY_DAO_IMPL,
    PAYMENT_DAO_IMPL,
    REFUND_DAO_IMPL,
    REGISTRATION_PAYMENT_DAO_IMPL,
    STAFF_DAO_IMPL,
    STAFF_SALARY_DAO_IMPL,
    STUDENTS_CLASS_DAO_IMPL,
    STUDENTS_DAO_IMPL,
    TUTOR_DAO_IMPL,
    TUTOR_SALARY_DAO_IMPL,
    USER_DAO_IMPL
}
